### ISSUE TITLE
Does not use a Linked List as the data structure

### ISSUE THREAD

**Issue by sudosimi** [Marcohj/Project-Cluster#1]
You move the list into an array. The requirements state that we should use only a linked-list as a data structure, and later a chained list that we can transform into a HashMap.

**Comment by Marcohj** [comment]
Argh...

Yea it's in my todo.... :-)

But i guess the only change needed is to change it to next when i create the entries?

I'll look at fix and reupload!

**Comment by sudosimi** [comment]
It's a bit more challenging to use Linked lists. You don't have indexes and
you have to figure out ways to find where you are in it. Meanwhile I'm
working for a solution too. I got the proper search without using any
arrays by using just a method that gets the page a word is on and goes
through the whole list.
I'm having problems with uploading to git-hub, but I'll put it manually if
my IDE doesn't comply.

2013/10/17 Marco H. Johannesen notifications@github.com

**Comment by Marcohj** [comment]
Uploaded a new version.

I get an weird error though... and i dont really understand why!

**Comment by sudosimi** [comment]
Oh... you need to set the file properly, you either run the file from cmd
with java SearchCmd_Task2 filename, and place files in src or bin( not sure)
I've set that from my IDE so I don't use cmd. instead of filename use the
line from your code

2013/10/17 Marco H. Johannesen notifications@github.com

**Comment by Marcohj** [comment]
Hmmm i get this error:

**Comment by Marcohj** [comment]
The local variable current may not have been initialized    Searcher.java   /Project Cluster/src    line 125    Java Problem

**Comment by Marcohj** [comment]
Works now ;-)

What is the difference between linked list and chained list? ;-I
